### ISSUE TITLE
import issue

### ISSUE THREAD

**Issue by mcash95** [Coding-with-Adam/Dash-by-Plotly#17]
from app import app
ImportError: cannot import name 'app' from 'app'

Hi,
I just watched your video to get started working with Dash. On attempting to build the files locally I ran into this issue.
I was wondering how you got around it in your project as i have pulled directly from the github here and am still having the issue.

Thanks,
Max

**Comment by Coding-with-Adam** [comment]
Hi @mcash95 can you please guide me to the github file in question.

**Comment by ravisamavedula** [comment]
Hi Adam,

Inside pages/histogram.py if i use "from app import app".I am getting below errror.
ImportError: cannot import name 'app' from partially initialized module 'app' (most likely due to a circular import)

How can get instance of app of inside page/
