### ISSUE TITLE
help with a project

### ISSUE THREAD

**Issue by bhavya-sukheja** [Coding-with-Adam/Dash-by-Plotly#20]
hey adam, hope are you doing well !
I've been given an assignment to create a some charts using Dash by plotly, and I'm having some trouble to execute it. I was given an excel file to work upon, and I watched your video on YT and found my way to your GitHub. I was wondering if you could help me execute it the way you've in your YT video.

**Comment by Coding-with-Adam** [comment]
Hi Bhavya,
I can't promise anything because I am working on the next YouTube video, but if I have a few minutes, I'll take a look.. Feel free to send me your code and CSV sheet to Adam@charming-data.com
