### ISSUE TITLE
ImportError: cannot import name 'app' from partially initialized module 'app' (most likely due to a circular import)

### ISSUE THREAD

**Issue by ravisamavedula** [Coding-with-Adam/Dash-by-Plotly#21]
Hi @Coding-with-Adam ,

Inside pages/histogram.py if i use "from app import app".I am getting the below error.
ImportError: cannot import name 'app' from partially initialized module 'app' (most likely due to a circular import)

How can get an instance of app of inside pages/ any component?

**Comment by Coding-with-Adam** [comment]
Hi @ravisamavedula 
I don't see the code line ""from app import app"" in the historgram.py file here:
https://github.com/Coding-with-Adam/Dash-by-Plotly/tree/master/Dash_More_Advanced_Shit/Multipage_app/pages

Are you referring to a different file?

**Comment by ravisamavedula** [comment]
Hi @Coding-with-Adam ,

I mean if I add that line historgram.py. I needed to use dash-uploader which needs app instance.
at that time i see this failure.
