### ISSUE TITLE
Sharing_Data_Multipage_app breaks on dash-labs==1.1.0

### ISSUE THREAD

**Issue by andrewbartels1** [Coding-with-Adam/Dash-by-Plotly#25]
`pip install dash-labs==1.1.0`

remove suppress_callback_exceptions=True

run app with `python app.py`

![image](https://user-images.githubusercontent.com/46938273/177825636-f07e7a5b-3254-43ef-b8f0-85b1b67e70ad.png)

`pip install dash-labs==1.0.0`

run app with `python app.py`

Interestingly enough, this still produces one error, but this might be a known one (however example works just fine):

![image](https://user-images.githubusercontent.com/46938273/177826139-4df15735-e463-4d42-8ee1-965249c3bfdd.png)

**Comment by Coding-with-Adam** [comment]
Thank you for alerting me to this @andrewbartels1 
I just removed the video from Youtube, because there is a new way to build multipage app with Dash and share data. The video showed the old way which is no longer recommended.

If you see any other issue, please let me know. Thank you,

**Comment by andrewbartels1** [comment]
Would you be so kind as to send a link to docs video for the newest supported way? 

Thank you!

**Comment by Coding-with-Adam** [comment]
Hi,Everything is in this post, including links to the docs. I hope to make a video on this topic in a couple of weeks. https://community.plotly.com/t/dash-2-5-released-easier-multi-page-apps-component-properties/64925/18Adam SchroederOwnerCharming Data LLC 118 E 124th ST #1808, New York, New York 10035   My Pronouns: He, him, his ¡Hablo español! 
      
        
        
          On Jul 8 2022, at 11:55 pm, andrewbartels1 ***@***.***> wrote:
          
        
        
          
Would you be so kind as to send a link to docs video for the newest supported way?
Thank you!
