### ISSUE TITLE
from dash import Dash, dash_table ImportError: cannot import name 'Dash' from partially initialized module 'dash' (most likely due to a circular import) (C:\Users\ADMIN\Desktop\vs\dash.py)

### ISSUE THREAD

**Issue by zainali60** [Coding-with-Adam/Dash-by-Plotly#26]

**Comment by zainali60** [comment]
from dash import Dash, dash_table
ImportError: cannot import name 'Dash' from partially initialized module 'dash' (most likely due to a circular import) (C:\Users\ADMIN\Desktop\vs\dash.py)
tell me about this error

**Comment by Coding-with-Adam** [comment]
hi @zainali60 
Is this code from a particular python file on my github repository?

**Comment by zainali60** [comment]
> hi @zainali60 Is this code from a particular python file on my github repository?

**Comment by Coding-with-Adam** [comment]
Great. I'm happy you solved it.

**Comment by SAAHMATHWORKS** [comment]
@arain60gb please let me know how you solved it
