### ISSUE TITLE
Link to the data source for Dash Bootstrap Spinner & Progress Bar video not working

### ISSUE THREAD

**Issue by mutumagitonga** [Coding-with-Adam/Dash-by-Plotly#56]
I have tried accessing **green_tripdata_2019-01.csv** data file from the provided Google drive link [here](https://drive.google.com/file/d/1Srm_mhf6oRb6R5kFijFzaZk6tye9Ugb0/view) which was included in this code [file](https://github.com/Coding-with-Adam/Dash-by-Plotly/blob/master/Bootstrap/spinners_bar.py).

**Comment by Coding-with-Adam** [comment]
Thank you for pointing that out, @mutumagitonga 
I just updated the link to the csv sheet. Not sure why the old link didn't work.

**Comment by mutumagitonga** [comment]
You are welcome @Coding-with-Adam  !
The new link you have added now works. 
I cannot guess what could have broken the first link but we can say all is well that ends well :)
