### ISSUE TITLE
Error in Dash2.0 solution 4: need MantineProvider to for mantine components.

### ISSUE THREAD

**Issue by delale** [Coding-with-Adam/Dash-by-Plotly#59]
As explained in the dash-mantine-components [Getting Started](https://www.dash-mantine-components.com/getting-started) page, the app needs to be wrapped around a `dmc.MantineProvider`, otherwise an error is thrown (only in debug mode) and the alert is not visible.
Proposed fix:
Change line 21 of [Good_to_Know/Dash2.0/Exercises/solution-4.py](https://github.com/Coding-with-Adam/Dash-by-Plotly/blob/master/Good_to_Know/Dash2.0/Exercises/solution-4.py) from
```py
app.layout = dbc.Container([mytitle, myalert, mygraph, dropdown])
```
to
```py
app.layout = dmc.MantineProvider([mytitle, myalert, mygraph, dropdown])
```

**Comment by Coding-with-Adam** [comment]
Thank you @delale . I just made the update on line 21 🙏🏻
